require("core.lazy")
require("core.base")
require("plugins.theme")
require("plugins.cmp")
require("plugins.mason")
require("plugins.lsconfig")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.nvim-tree")
require("plugins.lsp-zero")
require("plugins.autoclose")
require("plugins.codeium")

-- KeyMap
require("keymaps.keymaps")
